#include <iostream>
#include "Jungle.cpp"
#include "Animal.cpp"
#include "DomesticAnimal.cpp"
#include "WildAnimal.cpp"
#include "PetAnimal.cpp"
using namespace std;
int main() {
    int numOfAnimals;
    cin>>numOfAnimals;
    Jungle forest(numOfAnimals);
    for (int i = 0; i < numOfAnimals/2; i++){
        forest.AddAnimal(new DomesticAnimal());
        forest.AddAnimal(new WildAnimal());
    }
    if (numOfAnimals%2==1)
        forest.AddAnimal(new DomesticAnimal());
    forest.AddAnimal(new DomesticAnimal());
    forest.movement();              //1000 movement
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();              //1000 movement
    cout<<"Total Fell Animals in Pits!!: "<< forest.getTotalFall()<<endl;
    // now with pet & wild & domestic 
    cin>>numOfAnimals;
    Jungle forest(numOfAnimals);
    for (int i = 0; i < numOfAnimals/3; i++){
        forest.AddAnimal(new DomesticAnimal());
        forest.AddAnimal(new WildAnimal());
        forest.AddAnimal(new PetAnimal());
    }
    if (numOfAnimals%3==2){
        forest.AddAnimal(new DomesticAnimal());
        forest.AddAnimal(new PetAnimal());
    }
    else if (numOfAnimals%3==1)
        forest.AddAnimal(new DomesticAnimal());
    forest.AddAnimal(new DomesticAnimal());
    forest.movement();              //1000 movement
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();
    forest.movement();              //1000 movement
    cout<<"Total Fell Animals in Pits!!: "<< forest.getTotalFall()<<endl;
    return 0;
}
